server:
  port: 800

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nursing?serverTimezone=GMT%2B8
    username: root
    password: xjx@2020
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-idle: 5
      max-total: 20
      max-wait-millis: 3000
      initial-size: 5

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-handlers-package: com.xjx.nursing.typehandler
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.xjx.nursing.mapper : debug
